modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://github.com/Syconn/StarWarsMod/issues/new"
license = "All Rights Reserved"

[[mods]]
    modId = "swm"
    version = "${version}"
    displayName = "Star Wars Mod"
    authors = "Syconn"
    displayURL="https://modrinth.com/mod/syconns-star-wars-mod"
    updateJSONURL="https://raw.githubusercontent.com/Syconn/Syconn-Mod-Updates/refs/heads/main/StarWarsMod.json"
    description = '''
        A long time ago in a Galaxy Far Far Away
        '''
    logoFile = "StarWarsMod.png"
    displayTest="MATCH_VERSION"

[[dependencies.swm]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.swm]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.swm]]
modId = "architectury"
mandatory = true
versionRange = "[6.6.92,)"
ordering = "AFTER"
side = "BOTH"
