plugins {
    id 'org.jetbrains.kotlin.jvm'
}

architectury {
    common project.enabled_platforms.split(',')
}

loom {
    accessWidenerPath = project(':common').file("src/main/resources/swm.accessWidener")
}

dependencies {
    modImplementation "net.fabricmc:fabric-loader:$project.fabric_loader_version"
    modImplementation "dev.architectury:architectury:$project.architectury_api_version"

    compileOnly "mezz.jei:jei-${project.minecraft_version}-common-api:${project.jei_version}"
    modImplementation "dev.kosmx.player-anim:player-animation-lib-fabric:${project.player_anim}"
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
}

jar {
   duplicatesStrategy(DuplicatesStrategy.EXCLUDE)
}

repositories {
    mavenCentral()
}
kotlin {
    jvmToolchain(17)
}
