modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/Syconn/StarWarsMod/issues/new"
license = "All Rights Reserved"

[[mods]]
    modId = "swm"
    version = "${version}"
    displayName = "Star Wars Mod"
    authors = "Syconn"
    displayURL="https://modrinth.com/mod/syconns-star-wars-mod"
    updateJSONURL="https://raw.githubusercontent.com/Syconn/Syconn-Mod-Updates/refs/heads/main/StarWarsMod.json"
    description = '''
        A long time ago in a Galaxy Far Far Away
        '''
    logoFile = "StarWarsMod.png"

[[dependencies.swm]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.swm]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.swm]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "swm.mixins.json"

[[mixins]]
config = "swm.neoforge.mixins.json"
